add_newline = false
command_timeout = 1000
format = "$directory$git_branch  $character"
right_format = ""

[character]
error_symbol = '[\( ◠ ‿ ◠\)و](#d98992)'
success_symbol = '[\( ◠ ‿ ◠\)و](#7bb8ac)'
vimcmd_symbol = "[❮](#c6abd6)"

[directory]
use_logical_path = false
format = "[$path]($style)[$read_only]($read_only_style)"
home_symbol = "~"
read_only = " 󰌾"
style = "#d8dee9"
truncation_length = 4
truncate_to_repo = false
truncation_symbol = "…/"

[git_branch]
format = " [$symbol$branch]($style)"
style = "#87909f"
symbol = " "

[git_status]
disabled = true
