add_newline = false
command_timeout = 1000
format = "${custom.terminal}$directory$git_branch  $character"
right_format = ""

[character]
error_symbol = '[\( ◠ ‿ ◠\)و](#d98992)'
success_symbol = '[\( ◠ ‿ ◠\)و](#7bb8ac)'
vimcmd_symbol = "[❮](#c6abd6)"

[directory]
format = "[$path]($style)[$read_only]($read_only_style)"
home_symbol = "~"
read_only = " 󰌾"
style = "#d8dee9"
truncation_length = 4
truncate_to_repo = false
truncation_symbol = "…/"

[git_branch]
format = " [$symbol$branch]($style)"
style = "#87909f"
symbol = " "

[git_status]
disabled = true

[custom.terminal]
when = true
command = "printf '\\033]11;#282c34\\007\\033]10;#d8dee9\\007\\033]12;#7bb8ac\\007'"
format = "$output"
unsafe_no_escape = true
shell = ["/bin/sh"]
